apiVersion: v1
kind: Service
metadata:
  name: nginx-multitool-service
  namespace: dz8
spec:
  selector:
    app: nginx-multitool
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
